# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1ae3cc9d5aad0c2a2806b8109bebe75ca53ce1f3f0d0e440cd54973608819c203f48c54179b6486571b82862dcbadfa5322bc474a7809d2043a44872c598e7a

test:
  secret_key_base: 0624c2076a95a7432e29ce1de07a32651486383d2ef6d8ea47ebfd593896ad11e27ffb82426b15e5cbe29453d42a2acf50f51502150c4f093ae2b6ec42188e15

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
